config/routes.rb
R20130307Letsgitphysical::Application.routes.draw do
  root :to => 'home#index'
  resources :users, :only => [:index, :new, :create]
  resources :exercises, :only => [:index, :new, :create] do
    collection do
        get 'chart/:activity', :action => 'chart'
    end
  end
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/exercise.rb
# == Schema Information
#
# Table name: exercises
#
#  id         :integer          not null, primary key
#  activity   :string(255)
#  value      :float
#  unit       :string(255)
#  completed  :date
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Exercise < ActiveRecord::Base
  attr_accessible :activity, :value, :unit, :completed
  belongs_to :user, :inverse_of => :exercises
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)
#  password        :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  has_many :exercises, :inverse_of => :user
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate
  private
  def authenticate
    @auth = User.find(session[:user_id]) if session[:user_id].present?
  end
  def ensure_logged_in
    redirect_to(root_path) if @auth.nil?
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_filter :only_authorized
  def index
    @exercises = @auth.exercises.order(:activity).order(:completed)
    @activities = @auth.exercises.map(&:activity).uniq.sort
  end

  def new
    @exercise = Exercise.new
  end

  def create
    @auth.exercises << Exercise.create(params[:exercise])
    @exercises = @auth.exercises.order(:activity).order(:completed)
    @activities = @auth.exercises.map(&:activity).uniq.sort
  end

  def chart
    render :json => @auth.exercises.where(:activity => params[:activity])
  end

  private
  def only_authorized
    redirect_to(root_path) if @auth.nil?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
      user = User.where(:email => params[:email]).first
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to(root_path)
      else
        redirect_to(login_path)
      end
    end
    def destroy
      session[:user_id] = nil
      redirect_to(root_path)
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(:email)
  end
  def new
    @user = User.new
  end
  def create
    User.create(params[:user])
    @users = User.order(:email)

    respond_to do |format|
      format.html { redirect_to(users_path) }
      format.js {}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_nav
    if @auth.present?
      link_to(@auth.email, login_path, :method => :delete, :class => 'button alert')
    else
      link_to('Login', login_path, :class => 'button success')
    end
  end
end

app/views/exercises/_exercises.html.haml
- @exercises.each do |exercise|
  %ul
    %li= exercise.activity
    %li= exercise.value
    %li= exercise.unit

app/views/exercises/_form.html.haml
.row
  .large-3.columns
    = form_for @exercise, :remote => true do |f|
      = f.label :activity
      = f.text_field :activity, :autofocus => true
      = f.label :value
      = f.text_field :value
      = f.label :unit
      = f.text_field :unit
      = f.label :completed
      = f.text_field :completed
      = f.submit nil, :class => 'button radius'
  .large-9.columns

app/views/exercises/create.js.erb
$('#new_exercise').empty();
$('#exercises').empty().append('<%=j render(:partial => 'exercises') %>');

app/views/exercises/index.html.haml
#new_exercise
.row
  .large-4.columns
    .float
      = link_to('New', new_exercise_path, :remote => true, :class => 'button radius tiny success')
    .float
      = button_tag 'Chart', :class => 'button radius tiny', :id => 'show_chart'
    .float
      = select_tag 'activities', options_for_select(@activities.map{ |a| [a, a] })
    .clear
  .large-8.columns

#chart

%ol#exercises

app/views/exercises/new.js.erb
$('#new_exercise').append('<%=j render(:partial => 'form') %>');

app/views/home/homepage.html.erb
<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>Foundation 4</title>

  <link rel="stylesheet" href="css/normalize.css" />
  <link rel="stylesheet" href="css/app.css" />

  <script src="js/vendor/custom.modernizr.js"></script>

</head>
<body>

  <!-- body content here -->

  <script>
  document.write('<script src=' +
  ('__proto__' in {} ? 'js/vendor/zepto' : 'js/vendor/jquery') +
  '.js><\/script>')
  </script>
  <script src="js/foundation/foundation.js"></script>
  <script src="js/foundation/foundation.alerts.js"></script>
  <script src="js/foundation/foundation.clearing.js"></script>
  <script src="js/foundation/foundation.cookie.js"></script>
  <script src="js/foundation/foundation.dropdown.js"></script>
  <script src="js/foundation/foundation.forms.js"></script>
  <script src="js/foundation/foundation.joyride.js"></script>
  <script src="js/foundation/foundation.magellan.js"></script>
  <script src="js/foundation/foundation.orbit.js"></script>
  <script src="js/foundation/foundation.placeholder.js"></script>
  <script src="js/foundation/foundation.reveal.js"></script>
  <script src="js/foundation/foundation.section.js"></script>
  <script src="js/foundation/foundation.tooltips.js"></script>
  <script src="js/foundation/foundation.topbar.js"></script>
  <script>
  $(document).foundation();
  </script>
</body>
</html>

app/views/layouts/_body.erb
<div class="row">
  <div class="large-12 columns">
    <%= yield %>
  </div>
</div>

app/views/layouts/_footer.html.erb
  <footer class="row">
    <div class="large-12 columns">
      <hr />
      <div class="row">
        <div class="large-6 columns">
          <p>&copy; Copyright no one at all. Go to town.</p>
        </div>
        <div class="large-6 columns">
          <ul class="inline-list right">
            <li><a href="#">Link 1</a></li>
            <li><a href="#">Link 2</a></li>
            <li><a href="#">Link 3</a></li>
            <li><a href="#">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

app/views/layouts/_nav.html.erb
  <div class="row">
    <div class="large-12 columns">
      <div class="nav-bar right">
       <ul class="button-group">
         <li><%= link_to('Home', root_path, :class => 'button') %></li>
         <li><%= link_to('Users', users_path, :class => 'button') %></li>
         <li><%= link_to('Exercises', exercises_path, :class => 'button') %></li>
         <li><%= login_nav %></li>
        </ul>
      </div>
      <h1>Let's Get Physical. <small>I wanna get.</small></h1>
      <hr />
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>R20130307Letsgitphysical</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render :partial => 'layouts/nav' %>
<%= render :partial => 'layouts/body' %>
<%= render :partial => 'layouts/footer' %>
</body>

app/views/session/new.html.haml
.row
  .five.columns
    = form_tag '/login' do
      = label_tag :email
      = text_field_tag :email, nil, :autofocus => true
      = label_tag :password
      = password_field_tag :password
      = submit_tag 'Login', :class => 'button radius'
  .seven.columns

app/views/users/_form.html.haml
.row
  .large-3.columns
    = form_for @user, :remote => true do |f|
      = f.label :email
      = f.text_field :email, :autofocus => true
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation
      = f.password_field :password_confirmation
      = f.submit nil, :class => 'button radius'
  .large-9.columns

app/views/users/_users.html.haml
- @users.each do |user|
  %li= user.email

app/views/users/create.js.erb
$('#new_user').empty();
$('#users').empty().append('<%=j render(:partial => 'users') %>');

app/views/users/index.html.haml
= link_to('New', new_user_path, :class => 'button radius tiny success')
= link_to('New', new_user_path, :remote => true, :class => 'button radius tiny alert')

#new_user
%ol#users
  = render(:partial => 'users')

app/views/users/new.html.haml
%h3 New User
= render(:partial => 'form')

app/views/users/new.js.erb
$('#new_user').append('<%=j render(:partial => 'form') %>');